// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	nexxa "github.com/aussenseiter-VsRB/JHIC-BE/internal/domain/nexxa"
	mock "github.com/stretchr/testify/mock"
)

// AIClient is an autogenerated mock type for the AIClient type
type AIClient struct {
	mock.Mock
}

// Complete provides a mock function with given fields: ctx, messages, jsonMode
func (_m *AIClient) Complete(ctx context.Context, messages []nexxa.Message, jsonMode bool) (string, error) {
	ret := _m.Called(ctx, messages, jsonMode)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []nexxa.Message, bool) (string, error)); ok {
		return rf(ctx, messages, jsonMode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []nexxa.Message, bool) string); ok {
		r0 = rf(ctx, messages, jsonMode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []nexxa.Message, bool) error); ok {
		r1 = rf(ctx, messages, jsonMode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAIClient creates a new instance of AIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AIClient {
	mock := &AIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}