// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Embedder is an autogenerated mock type for the Embedder type
type Embedder struct {
	mock.Mock
}

// Embed provides a mock function with given fields: ctx, inputs
func (_m *Embedder) Embed(ctx context.Context, inputs []string) ([][]float32, error) {
	ret := _m.Called(ctx, inputs)

	if len(ret) == 0 {
		panic("no return value specified for Embed")
	}

	var r0 [][]float32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([][]float32, error)); ok {
		return rf(ctx, inputs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) [][]float32); ok {
		r0 = rf(ctx, inputs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]float32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, inputs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEmbedder creates a new instance of Embedder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmbedder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Embedder {
	mock := &Embedder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}