// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	chat "github.com/aussenseiter-VsRB/JHIC-BE/internal/domain/nexxa/chat"
	mock "github.com/stretchr/testify/mock"
)

// KnowledgeRepository is an autogenerated mock type for the KnowledgeRepository type
type KnowledgeRepository struct {
	mock.Mock
}

// Search provides a mock function with given fields: ctx, query, limit
func (_m *KnowledgeRepository) Search(ctx context.Context, query []float32, limit int) ([]chat.Chunk, error) {
	ret := _m.Called(ctx, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []chat.Chunk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []float32, int) ([]chat.Chunk, error)); ok {
		return rf(ctx, query, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []float32, int) []chat.Chunk); ok {
		r0 = rf(ctx, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]chat.Chunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []float32, int) error); ok {
		r1 = rf(ctx, query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKnowledgeRepository creates a new instance of KnowledgeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKnowledgeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KnowledgeRepository {
	mock := &KnowledgeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}